### ISSUE TITLE
Research: E-mail logo supporting dark mode

### ISSUE THREAD

**Issue by eirikbacker** [Mattilsynet/design#51]
Prøv å unngå dette:
![image](https://github.com/user-attachments/assets/08e8de28-72c7-451d-b919-133043fe6193)

-----

@eirikbacker har utviklet en fin copy/paste-løsning for epostsignaturer som ligger på [design.mattilsynet.no](https://design.mattilsynet.no/?path=/docs/profilering-e-postsignatur--docs)

@Moimoto har testet raskt og oppdaget at Outlook på desktop og web-applikasjon oppfører seg ulikt når epostsignaturen limes inn. Det samme kan være tilfelle på tvers av Mac/PC. Blir derfor viktig å teste godt før det tas i bruk.

**TODO:**
- [x] Endre mobilnummer til flg format: (XX XX XX XX) ihht Språkrådets retningslinjer
- [x] Sjekk med Arkiv om det er behov for felles postadresse (faren er at post sendes til besøksadresse …)
- [ ] Lenker blir blå istedenfor sorte (light mode) eller hvite (dark mode) ved copy/paste 
- [ ] I desktop-app på Mac blir font og fontstørrelse gitt av default settings i appen. (Avenir ble Aptos ved testing)
